### ISSUE TITLE
Different locations for node_modules folder and vue.config.js.

### ISSUE THREAD

**Issue by saileshkush95** [EugeneDae/django-vue-cli-webpack-demo#11]
This is working fine and also this is awesome. But I've a question, Actually I'm new to javascript and vuejs. But I'm enough familiar with django. Actually I only want to put public folder and src folder inside client. Except this i want to all types of files and folder outside from client. I didn't know how to achieve this one?

**Comment by EugeneDae** [comment]
I think it should be possible. Just give it a try?

Remember, this repo is **not** a boilerplate or starter project. Do not use it as a base for your own projects.

Instead, create a new Vue CLI project (`vue start client`) and a new Django project (`django-admin startproject server`), repeat changes from https://github.com/EugeneDae/django-vue-cli-webpack-demo/commit/7a3df2a8fe9bfa44ec4c6892cf4d8bbac903e589 and adjust paths in vue.config.js.

**Comment by saileshkush95** [comment]
Yes we can easily achieve, We need little bit configurations. Here is example boilerplate. https://github.com/saileshkush95/VueDjango.
