### ISSUE TITLE
Django apps

### ISSUE THREAD

**Issue by nerdoc** [EugeneDae/django-vue-cli-webpack-demo#3]
This is a really great and simple approach.
Have you thought of how Django apps (and their templates) could be included in this way?
Would it be possible to have "plugin" apps which "inject" their own frontend parts vie templates into the main template?

**Comment by EugeneDae** [comment]
Interesting question, but too broad. Can you provide example code of a Django app that needs to be included?

**Comment by nerdoc** [comment]
I'm developing a Django framework which enables applications to have plugins (not just Django apps, but real plug-ins which could extend that application).
When using SPA frontends like with Vue, I searched for a possibility to  add a "frontend" part to each of the plugins. I found a way, but it's a bit clumsy.
My project is called GDAPS (Generic Django Application Plugin System), located [here](https://gitlab.com/nerdocs/gdaps).

This was created to scratch my own itch - I'd like to create a medical record application, and it should be extensible, so I am trying to make that approach more generic.
Your project seems to be the much simpler approach as django-webpack-loader, and I just asked myself (and here you) if there would be a possibility to enable such a functionality.

ATM I created [vue-extionsions](https://github.com/nerdocs/vue-extensions) to serve the Javascript/Vue part of the game.
But it's not perfect, and it's not really as simple to use as I want it.

**Comment by EugeneDae** [comment]
I see. I'm afraid I'm of little help on this matter.

You may want to check another approach which can be used with Vue CLI apps as well, it is equally simple and it doesn't require django-webpack-loader as well:
https://pascalw.me/blog/2020/04/19/webpack-django.html

**Comment by nerdoc** [comment]
Whow, this is great. Thanks.
