### ISSUE TITLE
Easiest way to change config to make an MPA?

### ISSUE THREAD

**Issue by ihelmer07** [EugeneDae/django-vue-cli-webpack-demo#6]
I'm trying to make an MPA as I only need to sprinkle Vue in a few places around my existing Django project.
A few interactive forms etc.

I have thought about using Vue within the browser but I'd really like to use `.vue` components.

Setting up vue to output multiple pages is very straight forward via the `pages` attribute in `vue.config.js`.

Any help with configuring this project into a Vue MPA?

**Comment by EugeneDae** [comment]
Can't help you right now because I haven't worked with Vue for some time, sorry.

**Comment by ihelmer07** [comment]
I've figured out a way to turn this into an MPA - would you be open for a PR to describe it in the readme?

**Comment by EugeneDae** [comment]
Absolutely!
