### ISSUE TITLE
Are there any version dependencies?

### ISSUE THREAD

**Issue by chrisamow** [EugeneDae/django-vue-cli-webpack-demo#8]
Hi Eugene - great work, I really like the approach!

Is there any dependency on anything new?  Or do you expect it to work on older versions of django and (especially) vue.  There are other dependencies preventing me from using latest.

**Comment by EugeneDae** [comment]
Hi @chrisamow , thanks for feedback!  I'm pretty sure it should work with older versions of Django and Vue just fine.

Just to make things clear: Vue or Vue CLI are basically irrelevant here. In fact I'm now using this in a Django project that doesn't have any frontend framework at all. It is all about Webpack, Webpack Dev Server and html-webpack-plugin. You just configure html-webpack-plugin to output a valid Django template with necessary includes baked in. Then you extend it (via `{% extends %}`) in your Django templates, and that's it. The purpose of this repository is to show how to do that for a Vue CLI project, where the Webpack config can only be modified programmatically. But if you're not using Vue CLI, and/or you have direct access to the Webpack config, it's even easier.

**Comment by chrisamow** [comment]
Ah yes, thanks for that extra reiteration - having it all concise really made it click.  (And for some reason I forgot that {% was legit pass through for html already and I was trying to remember what the magic was for it not messing up the vue build. - gah!)

But I understand the bigger picture (independent of the framework) and that is a nice elegant way to do this.  I originally came here because django-webpack-loader was giving problems - I think I maybe had a complicated bundling situation messing things up.

Thanks again, I think this is a great pattern to follow for integrating javascript power into django!
